### ISSUE TITLE
[question] What prevents a bearer from removing an offline attenuation blocks' caveat?

### ISSUE THREAD

**Issue by twitchyliquid64** [biscuit-auth/biscuit#91]
Hi!

Apologies for the smooth-brain question: I'm sure this is trivial I just don't understand or am getting confused.

I was reading the crypto part of the spec but couldn't piece together how you maintain integrity in the case of offline attenuation.

Imagine a scenario where some intermediate adds a caveat via offline attenuation or something, before passing it on to some other entity to use. Because its offline, presumably the intermediate doesn't have control of the root key used to originally mint the biscuit, so it has to key using something random. Im guessing this is what the reference is to `pk_n` is. 

But if a biscuit is just a chain of blocks which are based on the block preceding, and the private key is also carried along:

https://github.com/biscuit-auth/biscuit/blob/43369593bc3dfbe21e65c5569c3c3527b797434f/SPECIFICATIONS.md?plain=1#L583

Whats to stop an evil intermediary from just dropping the last block and (if needed) adjusting the rest of the biscuit to match based on knowledge of the private key?

**Comment by Geal** [comment]
the private key they get in the last block as not been used to sign anything yet.
let's say you have a 2-block token. You get:
```
Block 1:
- data 1
- public key 1
- signature = sign(root private key, data 1 + public key 1)

Block 2:
- data 2
- public key 2
- signature = sign(private key 1, data 2 + public key 2)

Last block:
- private key 2
```

When verifying a token, we check that the chain of signatures is ok, and the last step is verifying that the private key in the last block matches the public key signed in the preceding block.
If the last block is not present, verification will fail. If the private key does not match (because the preceding block was removed or modified), verification will fail to

**Comment by twitchyliquid64** [comment]
Ahhh, that makes sense. Thanks!
